- name: permit the following ports on master node
  firewalld:
    port: "{{ item.port }}/{{ item.proto }}"
    permanent: yes
    immediate: yes
    state: enabled
  notify:
    - reload service firewalld

  with_items:
    - {port: "6443", proto: "tcp"}
    - {port: "2379-2380", proto: "tcp"}
    - {port: "10250-10252", proto: "tcp"}
