- name: add Kubernetes' YUM repository
  yum_repository:
    name: Kubernetes
    description: Kubernetes YUM repository
    baseurl: "{{ kubernetes_repo_baseurl }}"
    gpgkey: "{{ kubernetes_repo_gpgkey }}"
    gpgcheck: yes

- name: install kubelet
  yum:
      name: kubelet
      state: present
      update_cache: true

- name: install kubeadm
  yum:
      name: kubeadm
      state: present

- name: start kubelet
  service:
    name: kubelet
    enabled: yes
    state: started
